### ISSUE TITLE
Unrecognized IAM permissions: catalog-admin

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-service-catalog-admin-guide#1]
Hi,

I don't see catalog-admin in the services for IAM policies when trying to build an IAM policy.  I also don't see any of the actions, like the ones listed 

catalog-admin:ListPortfolios
catalog-admin:SearchListings

I also see catalog-admin in the managed policy ServiceCatalogAdminReadOnly.

**Comment by ha-king** [comment]
any updates here ???

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
