### ISSUE TITLE
Wrong Policy Displayed - Step 6: Add a Launch Constraint to Assign an IAM Role

### ISSUE THREAD

**Issue by drewmullen** [awsdocs/aws-service-catalog-admin-guide#15]
https://docs.aws.amazon.com/servicecatalog/latest/adminguide/getstarted-launchconstraint.html

the rendered docs show the below policy, which is incorrect as its missing the service catalog line items. luckily the github [still has working files](https://github.com/awsdocs/aws-service-catalog-admin-guide/blob/master/doc_source/getstarted-launchconstraint.md). Not sure how the rendered content is different than the git content (that hasnt changed in 2 years).

```json
{
   "Version":"2012-10-17",
   "Statement":[
      {
         "Effect":"Allow",
         "Action":[
            "s3:GetObject"
         ],
         "Resource":"*",
         "Condition":{
            "StringEquals":{
               "s3:ExistingObjectTag/servicecatalog:provisioning":"true"
            }
         }
      }
   ]
}
```

**Comment by drewmullen** [comment]
can anyone comment on this? how are the docs rendered it not from github?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
