### ISSUE TITLE
Broken link in “Logging AWS Service Catalog API calls using AWS CloudTrail”

### ISSUE THREAD

**Issue by sftim** [awsdocs/aws-service-catalog-admin-guide#18]
[Logging AWS Service Catalog API calls using AWS CloudTrail](https://docs.aws.amazon.com/servicecatalog/latest/adminguide/logging-using-cloudtrail.html) states
> All AWS Service Catalog actions are logged by CloudTrail and are documented in the https://linkto.APIref.topic. 

That hyperlink is an invalid placeholder.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
