### ISSUE TITLE
AWS Managed Policy ServiceCatalogEndUserAccess

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-service-catalog-admin-guide#2]
The Managed Policy AWSServiceCatalogEndUserAccess gives out catalog-user:* which is an unrecognized service in IAM, I also don't see any documentation here that details what catalog-user does and what the supported actions are.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
