### ISSUE TITLE
No Documentation on AWS Managed Policy: ServiceCatalogAdminReadOnly

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-service-catalog-admin-guide#3]
ServiceCatalogAdminReadOnly has these actions and services which aren't recognized in the IAM console (also aren't listed):

                "catalog-admin:DescribeConstraints",
                "catalog-admin:DescribeListingForProduct",
                "catalog-admin:DescribeListings",
                "catalog-admin:DescribePortfolios",
                "catalog-admin:DescribeProductVersions",
                "catalog-admin:GetPortfolioCount",
                "catalog-admin:GetPortfolios",
                "catalog-admin:GetProductCounts",
                "catalog-admin:ListAllPortfolioConstraints",
                "catalog-admin:ListPortfolioConstraints",
                "catalog-admin:ListPortfolios",
                "catalog-admin:ListPrincipalConstraints",
                "catalog-admin:ListProductConstraints",
                "catalog-admin:ListResourceUsers",
                "catalog-admin:ListTagsForResource",
                "catalog-admin:SearchListings",
                "catalog-user:*",

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
