### ISSUE TITLE
Missing Constraint in Constraint Listing

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-service-catalog-admin-guide#5]
The listing of constraints here has 4 types so far: Launch, Notification, Template, and StackSet.

However, in the AWS Service Catalog console, I see 5 now: Launch, Notification, Template, StackSet, and Tag Update.  Tag Update seems to be missing in the readme (Tag Update: Allows you to update tags after the product has been provisioned.)

https://docs.aws.amazon.com/servicecatalog/latest/adminguide/portfoliomgmt-constraints.html
https://github.com/awsdocs/aws-service-catalog-admin-guide/blob/master/doc_source/portfoliomgmt-constraints.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
